#!/bin/bash

# Function to extract task id from branch name
extract_task_id() {
	branch_name="$1"
	if [[ $branch_name =~ ^sc-([0-9]+)- ]]; then
		echo "${BASH_REMATCH[1]}"
	fi
}

# Function to modify the commit message
modify_commit_message() {
	commit_message="$1"
	deploy_suffix="$2"
	branch_name=$(git rev-parse --abbrev-ref HEAD)
	task_id=$(extract_task_id "$branch_name")
	if [ -n "$task_id" ]; then
		commit_message="[sc-$task_id] $commit_message"
		if [ "$deploy_suffix" == "true" ]; then
			commit_message="$commit_message [deploy-rc]"
		fi
	fi
	echo "$commit_message"
}

# Read commit message and deploy flag from arguments
commit_message="$1"
deploy_flag="$2"

# Check if the commit message is empty
if [ -z "$commit_message" ]; then
	echo "A commit message is required."
	exit 1
fi

# Check if deploy flag is provided
if [[ "$deploy_flag" == "-d" || "$deploy_flag" == "--deploy" ]]; then
	deploy=true
else
	deploy=false
fi

# Modify the commit message
modified_message=$(modify_commit_message "$commit_message" "$deploy")

# Output the modified commit message
echo "$modified_message"
git commit -m "$modified_message"
