#!/bin/bash

# Backend directory
backend_dir="~/projects/agency-directory/"

# Frontend directory
frontend_dir="~/projects/agency-directory-profile/"

# Start the backend service in a new tmux session
tmux new-session -d -s backend_service -n api "cd $backend_dir && run_back; $SHELL"
# Counter for the dynamic timer
counter=1
timeout=60 # Timeout in seconds

# Check if the backend service is ready to accept requests
until nc -z localhost 8081; do
	echo -ne "Waiting for backend service to be available on port 8081... ${counter}s\r"
	sleep 1
	((counter++))

	if [ "$counter" -gt "$timeout" ]; then
		echo "Backend service did not start within $timeout seconds. Exiting."
		exit 1
	fi
done

echo "Backend service is now available on port 8081."

# Return to frontend tmux session
tmux switch-client -t "$frontend_dir"

# Create a new window for running npm run dev
tmux new-window -n build -c "$frontend_dir" "npm run dev"
